In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/Atlantic_Spain.csv")
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [4]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  datetime64[ns]
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(4), object(4)
memory usage: 1.9+ MB

In [6]:
df = df.drop_duplicates()

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
# Normalizing 'song', 'artist' and 'album_type'
df['song'] = df['song'].str.lower().str.strip()
df['artist'] = df['artist'].str.lower().str.strip()
df['album_type'] = df['album_type'].str.lower().str.strip()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27785 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27785 non-null  datetime64[ns]
 1   position         27785 non-null  int64
 2   song             27785 non-null  object
 3   artist           27785 non-null  object
 4   popularity       27785 non-null  int64
 5   duration_ms      27785 non-null  int64
 6   album_type       27785 non-null  object
 7   total_tracks     27785 non-null  int64
 8   is_explicit      27785 non-null  bool
 9   album_cover_url  27785 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(4), object(4)
memory usage: 2.1+ MB

In [10]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [11]:
df.to_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/normalized_songs.csv", index=False)

In [12]:
data = pd.read_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/normalized_songs.csv")
data.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [13]:
data.groupby('date').size()

date
2024-05-18    50
2024-05-19    50
2024-05-20    50
2024-05-21    50
2024-05-22    50
              ..
2025-11-23    50
2025-11-24    50
2025-11-25    50
2025-11-26    50
2025-11-27    50
Length: 555, dtype: int64

In [14]:
#Check Playlist Size per Day, Top-50 playlist must contain exactly 50 songs per day.
data.groupby('date').size().unique()

array([50, 85])

In [15]:
data = data.groupby('date').filter(lambda x: len(x) == 50)

In [16]:
data.groupby('date').size().unique()

array([50])

In [17]:
#Validate Position Column, Position should only be 1–50.
data['position'].describe()

count    27700.00000
mean        25.50000
std         14.43113
min          1.00000
25%         13.00000
50%         25.50000
75%         38.00000
max         50.00000
Name: position, dtype: float64

In [18]:
data = data[(data['position'] >= 1) & (data['position'] <= 50)]

In [19]:
data.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [25]:
#Clean Album Type Column
data['album_type'].unique()

array(['single', 'album'], dtype=object)

In [24]:
data['album_type'] = data['album_type'].str.lower().str.strip()

In [26]:
data['is_explicit'] = data['is_explicit'].astype(bool)

In [27]:
data

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,duration_min
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...,3.181817
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...,3.133100
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...,2.846417
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...,3.242383
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...,3.161133
...,...,...,...,...,...,...,...,...,...,...,...
27780,2025-11-27,46,celine (with kidd keo),ghost killer track & kidd keo,73,176017,single,1,False,https://i.scdn.co/image/ab67616d0000b273892224...,2.933617
27781,2025-11-27,47,vacile,yan block,78,140239,single,1,True,https://i.scdn.co/image/ab67616d0000b273b7a46e...,2.337317
27782,2025-11-27,48,rapido (with cris mj),dei v,76,146000,album,16,True,https://i.scdn.co/image/ab67616d0000b2734258ad...,2.433333
27783,2025-11-27,49,peligrosa,floyymenor,83,134930,album,7,True,https://i.scdn.co/image/ab67616d0000b273200e2b...,2.248833
27784,2025-11-27,50,luna,feid,88,196800,album,10,False,https://i.scdn.co/image/ab67616d0000b273f1aad8...,3.280000

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27700 entries, 0 to 27699
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27700 non-null  object
 1   position         27700 non-null  int64
 2   song             27700 non-null  object
 3   artist           27700 non-null  object
 4   popularity       27700 non-null  int64
 5   duration_ms      27700 non-null  int64
 6   album_type       27700 non-null  object
 7   total_tracks     27700 non-null  int64
 8   is_explicit      27700 non-null  bool
 9   album_cover_url  27700 non-null  object
 10  duration_min     27700 non-null  float64
dtypes: bool(1), float64(1), int64(4), object(5)
memory usage: 2.1+ MB

In [29]:
data = data.reset_index(drop=True)

In [31]:
#Create Unique Song ID
data['song_id'] = data['song'] + "_" + data['artist']

In [32]:
data.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url,duration_min,song_id
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...,3.181817,supernova_saiko
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...,3.133100,el tonto_lola indigo
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...,2.846417,acróstico_shakira
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...,3.242383,beso_rosalía & rauw alejandro
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...,3.161133,el merengue_marshmello & manuel turizo

In [33]:
#Sort Dataset
data = data.sort_values(by=['song_id','date'])

In [36]:
data = data.drop(columns=['album_cover_url'])

In [37]:
data.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,duration_min,song_id
18889,2025-06-02,40,0 confianza,rvfv,35,217500,album,20,False,3.625,0 confianza_rvfv
19030,2025-06-05,31,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
19074,2025-06-06,25,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
19122,2025-06-07,23,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv
19172,2025-06-08,23,0 confianza,rvfv,57,217500,album,20,False,3.625,0 confianza_rvfv

In [38]:
data.to_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/normalized_2_songs.csv", index=False)