In [1]:
import pandas as pd 
import numpy as np

In [12]:
df = pd.read_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/Atlantic_Spain.csv")
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,Supernova,Saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,18-05-2024,2,EL TONTO,Lola Indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,18-05-2024,3,Acróstico,Shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,18-05-2024,4,BESO,ROSALÍA & Rauw Alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,18-05-2024,5,El Merengue,Marshmello & Manuel Turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [14]:
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  datetime64[ns]
 1   position         27800 non-null  int64
 2   song             27800 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(4), object(4)
memory usage: 1.9+ MB

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
# Normalizing 'song', 'artist' and 'album_type'
df['song'] = df['song'].str.lower().str.strip()
df['artist'] = df['artist'].str.lower().str.strip()
df['album_type'] = df['album_type'].str.lower().str.strip()

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27785 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27785 non-null  datetime64[ns]
 1   position         27785 non-null  int64
 2   song             27785 non-null  object
 3   artist           27785 non-null  object
 4   popularity       27785 non-null  int64
 5   duration_ms      27785 non-null  int64
 6   album_type       27785 non-null  object
 7   total_tracks     27785 non-null  int64
 8   is_explicit      27785 non-null  bool
 9   album_cover_url  27785 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(4), object(4)
memory usage: 2.1+ MB

In [20]:
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,2024-05-18,1,supernova,saiko,84,190909,single,1,False,https://i.scdn.co/image/ab67616d0000b273c3f5b9...
1,2024-05-18,2,el tonto,lola indigo,83,187986,album,11,False,https://i.scdn.co/image/ab67616d0000b273daab36...
2,2024-05-18,3,acróstico,shakira,81,170785,single,1,False,https://i.scdn.co/image/ab67616d0000b273bd6bbd...
3,2024-05-18,4,beso,rosalía & rauw alejandro,96,194543,single,3,False,https://i.scdn.co/image/ab67616d0000b2734d6cf0...
4,2024-05-18,5,el merengue,marshmello & manuel turizo,91,189668,single,1,False,https://i.scdn.co/image/ab67616d0000b273f40467...

In [21]:
df.to_csv("/Users/PUSHPAK/OneDrive/Desktop/Spain_Project/data/normalized_songs.csv", index=False)